Run npm run build -- Release \

> brave-core@1.91.27 build
> node ./build/commands/scripts/commands.js build Release --target_os ios --target_arch arm64 --target_environment device --gn enable_brave_ads:false --gn enable_brave_rewards:false --gn enable_brave_vpn:false

node:fs:440
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open '/Users/runner/work/src/brave/package.json'
    at Object.readFileSync (node:fs:440:20)
    at #loadPackageJson (file:///Users/runner/work/brave-core/brave-core/build/commands/lib/envConfig.ts:303:35)
    at new EnvConfig (file:///Users/runner/work/brave-core/brave-core/build/commands/lib/envConfig.ts:37:51)
    at file:///Users/runner/work/brave-core/brave-core/build/commands/lib/config.js:20:19
    at ModuleJob.run (node:internal/modules/esm/module_job:377:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:671:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/runner/work/src/brave/package.json'
}

Node.js v24.11.1
Error: Process completed with exit code 1.
